name: Code Freeze
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
  schedule:
    - cron: "*/5 * * * *" # Every 30 minutes

jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - uses: yykamei/block-merge-based-on-time@v2.1.55
        with:
          timezone: Asia/Singapore
          after: "17:00 on Thursday"
          before: "17:05 on Thursday"
          base-branches: "uat"