name: Code Freeze
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
  schedule:
    - cron: ${{ vars.CODEFREEZE_CRON }}

jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - uses: yykamei/block-merge-based-on-time@v2.1.55
        with:
          timezone: Asia/Singapore
          after: ${{ vars.CODEFREEZE_AFTER }}
          before: ${{ vars.CODEFREEZE_BEFORE }}
          base-branches: ${{ vars.CODEFREEZE_BASE_BRANCHES }}